apiVersion: apps/v1
kind: Deployment
metadata:
  name: swissgeol-asset-app
  namespace: swissgeol-asset
  annotations:
    keel.sh/policy: force
    keel.sh/match-tag: 'true'
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swissgeol-asset-app
  template:
    metadata:
      labels:
        app: swissgeol-asset-app
    spec:
      containers:
      - name: swissgeol-asset-app
        image: ghcr.io/geoadmin/swissgeol-asset-app:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: geoadmin-ghcr-registry
      


      