apiVersion: apps/v1
kind: Deployment
metadata:
  name: swissgeol-asset-elasticsearch
  namespace: swissgeol-asset
  annotations:
    keel.sh/policy: force
    keel.sh/match-tag: 'true'
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swissgeol-asset-elasticsearch
  template:
    metadata:
      labels:
        app: swissgeol-asset-elasticsearch
    spec:
      volumes:
        - name: swissgeol-asset-elasticsearch-volume
          persistentVolumeClaim:
            claimName: swissgeol-asset-elasticsearch-int-volume
      containers:
        - name: swissgeol-asset-elasticsearch
          image: ghcr.io/geoadmin/swissgeol-search-elasticsearch:latest
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: '-Xms1024m -Xmx1024m'
            - name: ELASTIC_USERNAME
              value: elastic
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: swissgeol-asset-secrets
                  key: elasticPassword
            - name: xpack.security.enabled
              value: 'true'
            - name: xpack.encryptedSavedObjects.encryptionKey
              valueFrom:
                secretKeyRef:
                  name: swissgeol-asset-secrets
                  key: elasticEncryptionKey
            - name: bootstrap.memory_lock
              value: 'true'
          resources:
            limits:
              cpu: '4'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 2Gi
          volumeMounts:
            - name: swissgeol-asset-elasticsearch-volume
              mountPath: /usr/share/elasticsearch/data  
      restartPolicy: Always
      securityContext:
        fsGroup: 0
      imagePullSecrets:
      - name: geoadmin-ghcr-registry