#--------------------------------------
# rewrite auth
#--------------------------------------
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-auth-rewrite
  namespace: {{ .Release.Namespace }}  
spec:
  stripPrefix:
    prefixes:
      - /auth
---
#--------------------------------------
# rewrite kibana
#--------------------------------------
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:  
  name: {{ .Release.Name }}-kibana-rewrite
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - /kibana
---
#--------------------------------------
# rewrite elasticsearch
#--------------------------------------
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:  
  name: {{ .Release.Name }}-elasticsearch-rewrite
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - /elasticsearch
---
#--------------------------------------
# whitelist 
#--------------------------------------
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-whitelist
  namespace: {{ .Release.Namespace }}  
spec:
  ipWhiteList:
    sourceRange:
      - 62.202.47.154
