apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Namespace }}-registry
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Value.dockerconfigjson}}
type: kubernetes.io/dockerconfigjson