apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  authDbCon: {{ .Values.authDbCon}}
  gotrueJwtSecret: {{ .Values.gotrueJwtSecret}}
  apiDbCon: {{ .Values.apiDbCon}}
  elasticEncryptionKey: {{ .Values.elasticEncryptionKey}}
  elasticPassword: {{ .Values.elasticPassword}}
  s3AccessKeyId: {{ .Values.s3AccessKeyId}}
  s3SecretAccessKey: {{ .Values.s3SecretAccessKey}}
